spring.application.name=taskflow-backend
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/taskflow_db}

server.port=8081

jwt.secret=${JWT_SECRET:TaskFlowSecretKeyForJWTTokenGeneration2024SuperSecure}
jwt.expiration=86400000
